### ISSUE TITLE
Publish on Google Play?

### ISSUE THREAD

**Issue by floogulinc** [Open-RIO/ToastDroid#1]
Do you have any plans to publish this on Google Play?

**Comment by JaciBrunning** [comment]
I do indeed, although unfortunately my Debit Card doesn't work online, so I'm in contact with my Bank so I can pay the $25 registration fee on the Play Store :)

**Comment by floogulinc** [comment]
I have an active developer account, I could publish it if you want.

**Comment by JaciBrunning** [comment]
I wanna try and hold it off a bit before kickoff, there's still a few things I want to figure out before publishing (potential integration with a TBD project)
